version: '2'

services:
  user:
    image: yiisoftware/yii2-php:7.3-apache
    volumes:
      - ./:/app
    networks:
      - backend
    environment:
      DB_HOST: 'user_db'
      DB_NAME: 'user'
      DB_PASS: root
    labels:
     - "traefik.backend=user"
     - "traefik.frontend.rule=Host:api.user.local"
     - "traefik.port=80"

  user_db:
    image: mariadb:10.4
    restart: always
    volumes:
     - user-vol:/var/lib/mysql
    environment:
     MYSQL_ROOT_PASSWORD: root
    ports:
     - 3311:3306
    networks:
      - backend

##### PROXY
  proxy:
    image: traefik:1.7.6
    restart: always
    command: --web --docker --docker.domain=local
    ports:
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./docker/config/proxy/traefik.toml:/etc/traefik/traefik.toml
    labels:
     - "traefik.backend=proxy"
     - "traefik.frontend.rule=Host:proxy.local"
     - "traefik.port=8080"
    networks:
      - backend
     
networks:
  backend:

####VOLUMES
volumes:
  user-vol: