<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "usuario_modulo".
 *
 * @property integer $userid
 * @property integer $moduloid
 * @property string $create_at
 *
 * @property \app\models\Modulo $modulo
 * @property \app\models\User $user
 * @property string $aliasModel
 */
abstract class UsuarioModulo extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'usuario_modulo';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['userid', 'moduloid'], 'required'],
            [['userid', 'moduloid'], 'integer'],
            [['create_at'], 'safe'],
            [['userid', 'moduloid'], 'unique', 'targetAttribute' => ['userid', 'moduloid']],
            [['moduloid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Modulo::className(), 'targetAttribute' => ['moduloid' => 'id']],
            [['userid'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['userid' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'userid' => 'Userid',
            'moduloid' => 'Moduloid',
            'create_at' => 'Create At',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getModulo()
    {
        return $this->hasOne(\app\models\Modulo::className(), ['id' => 'moduloid']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'userid']);
    }




}
